In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from expand_subgraph import ExpandSubgraph
from model_2 import GNN_auto, Projector
import pickle as pkl
import numpy as np
import torch
from load_data import DataLoader
# from loader2 import DataLoader2 as GnnDataLoader
from reasoning_module2_ import ReasoningModule2 as ReasoningModule

KeyboardInterrupt: 

## Load graph artifacts:

In [ ]:
from data_utils import id2ent, ent2name, id2rel, rel2id

#### Load queries

In [ ]:
with open("knowledge_graph/queries/CWQ_sim_queries2.pkl", "rb") as f:
    queries = pkl.load(f)
id_query = 32
queries[id_query]

{'query_type': ('e', ('r',)),
 'raw_query': (5625, (132,)),
 'named_query': ('MC_Hammer',
  ('+/people/person/places_lived./people/place_lived/location',)),
 'transformed_query': 'Where did MC Hammer live?',
 'answers_id': [2320],
 'answers': ['Oakland'],
 'natural_query': 'Where did MC Hammer live?',
 'gold_path': [[5625, 132, 2320]],
 '1_hop_edges': [[5625, 48, 2320], [5625, 132, 2320], [5625, 320, 2320]]}

In [ ]:
type(queries[id_query]['gold_path'][0])

list

## Load sampler

In [ ]:
class Config:
    data_path = 'knowledge_graph/KG_data/FB15k-237-betae'
    seed = 1234
    k_rel = 4 # beams
    k_cands = 120
    depth = 2 # max depth of subgraph
    cands_lim = 1024
    gpu = 0
    fact_ratio = 1.0
    val_num = -1 # how many triples are used as the validate set
    add_manual_edges = False
    remove_1hop_edges = True
    not_shuffle_train = False
    device = "cuda:0"

In [ ]:
args = Config()
loader = DataLoader(args, mode='train')

# loader.shuffle_train()
train_graph = loader.train_graph
train_graph_homo = list(set([(h,t) for (h,r,t) in train_graph]))

args.n_ent = loader.n_ent
args.n_rel = loader.n_rel

544230 0
==> removing 1-hop links...
==> done


In [ ]:
len(train_graph)

544230

### Init sampler

In [ ]:
GoG_args = {
    'drop_ratio': 0.4,
}

sampler = ExpandSubgraph(
    args.n_ent, args.n_rel, train_graph_homo, train_graph, args,
    GoG_simulation=True,
    GoG_args=GoG_args
)

In [ ]:
sampler.assign_query(queries[id_query])
subgraph_data = sampler.sampleSubgraph()

In [ ]:
print(len(sampler.orignal_edge_index), len(sampler.edge_index))

544230 544224


In [ ]:
def count_path_to_ans(id_query, subgraph_data):
    summ = 0
    for ans in queries[id_query]['answers_id']:
        cnt = 0
        for edges in subgraph_data[2]:
            if ans in edges[[0,2]]:
                cnt += 1

        summ += cnt
        # print(ans, cnt)
        print(summ)

In [ ]:
count_path_to_ans(id_query, subgraph_data)

0


### Init model

In [ ]:
args.n_rel=237

In [ ]:
modelPath = "weights/finetune/avid-forest-122.pt"
checkpoint = torch.load(modelPath, map_location=torch.device("cuda:0"), weights_only=False)

class GNN_config:
    n_layer = 8
    active_layer = 3
    hidden_dim = 64
    attn_dim = 4
    dropout = 0.3
    n_ent = 1024 # subgraph size
    n_rel = 237
    train_ver = 20
    shortcut = True
    readout = 'linear'
    concatHidden = True
    initializer = 'relation'
    # llm_description_emb_path = "data_for_CL/llm_description_aligned_emb.pkl"
    # ## 474 relations / 20 versions each / 4096 dimensional
    # with open(llm_description_emb_path, "rb") as f:
    #     llm_description_aligned_emb = pkl.load(f)
    # llm_emb = list(llm_description_aligned_emb.values())
    # llm_emb = torch.stack(llm_emb, dim=0)
    # pretrain_model_path = "weights/finetune/avid-forest-122.pt"
    # del(llm_description_aligned_emb)


gnn_model = GNN_auto(GNN_config, loader)
gnn_model.load_state_dict(checkpoint['gnn_model'])
gnn_model = gnn_model.to(torch.device("cuda:0"))


In [ ]:
class Projector_config:
    n_layers = 8
    in_dim = 4096
    hidden_dims = [512, 256]
    out_dim = 64

projector_model = Projector(Projector_config.in_dim, Projector_config.hidden_dims, Projector_config.out_dim, Projector_config.n_layers)
projector_model.load_state_dict(checkpoint['projector'])

<All keys matched successfully>

In [ ]:
reasoning_module = ReasoningModule(sampler,
                                   subgraph_data,
                                   gnn_model,
                                   projector_model,
                                   "gpt-3.5-turbo") 
# gpt-4o, gpt-3.5-turbo, "meta-llama/Llama-3.1-8B-Instruct"

In [ ]:
subgraph_data

(tensor([   16,    30,    41,  ..., 13776, 13805, 13925]),
 tensor([0, 0, 0,  ..., 0, 0, 0]),
 tensor([[3793,  155, 5797],
         [3793,  155, 3605],
         [3793,  247, 2188],
         ...,
         [7329,  239, 5910],
         [9201,  106, 8357],
         [9201,  107, 8357]]))

In [ ]:
ent_dict = {}
for idx in subgraph_data[0].cpu().numpy():
    ent_dict[idx.item()] = ent2name[id2ent[idx]]
rel_dict = {}
for idx in subgraph_data[2].cpu().numpy()[:,1]:
    rel_dict[idx.item()] = id2rel[idx]

In [ ]:
ent_dict.items()
rel_dict.items()

dict_items([(155, '-/base/popstra/celebrity/dated./base/popstra/dated/participant'), (247, '-/base/popstra/celebrity/canoodled./base/popstra/canoodled/participant'), (154, '+/base/popstra/celebrity/dated./base/popstra/dated/participant'), (170, '+/people/person/spouse_s./people/marriage/type_of_union'), (171, '-/people/person/spouse_s./people/marriage/type_of_union'), (239, '-/celebrities/celebrity/celebrity_friends./celebrities/friendship/friend'), (238, '+/celebrities/celebrity/celebrity_friends./celebrities/friendship/friend'), (328, '+/celebrities/celebrity/sexual_relationships./celebrities/romantic_relationship/celebrity'), (329, '-/celebrities/celebrity/sexual_relationships./celebrities/romantic_relationship/celebrity'), (107, '-/base/popstra/celebrity/breakup./base/popstra/breakup/participant'), (106, '+/base/popstra/celebrity/breakup./base/popstra/breakup/participant'), (385, '-/people/person/spouse_s./people/marriage/spouse'), (384, '+/people/person/spouse_s./people/marriage/s

In [ ]:
reasoning_module.assign_query(queries[id_query])
reasoning_module.assign_subgraph(subgraph_data, (id2ent, id2rel))


In [ ]:
reasoning_module.

### Inference on your queries

In [ ]:
def count_path_to_ans(id_query, subgraph_data):
    sum_cnt = 0
    for ans in queries[id_query]['answers_id']:
        cnt = 0
        for edges in subgraph_data[2]:
            if ans in edges[[0,2]]:
                cnt += 1
        sum_cnt += cnt
        print(ent2name[id2ent[ans]], "|| count: " + str(cnt))
        return sum_cnt

In [ ]:
predictions = []
ground_truths = []
cands = []

In [ ]:
for query in queries[:1]:
    ground_truths.append(query['answers'])
    print(query['natural_query'])
    subgraph_data = sampler.sampleSubgraph(query)
    
    reasoning_module.assign_query(query)
    reasoning_module.assign_subgraph(subgraph_data)
    reasoning_module.reasoning()
    results = reasoning_module.result
    predictions.append([results])
    cands.append(reasoning_module.cands)

Who was a romantic partner of Howard Hughes with whom he had a breakup?


AttributeError: 'ReasoningModule2' object has no attribute 'gnn_forward'

In [ ]:
a

In [ ]:
dict_t = {"predctions": predictions, "cands": cands, "ground_truths": ground_truths}

with open("attempt_4_1_100_queries.pkl", "wb") as f:
    pkl.dump(dict_t, f)


In [ ]:
from evaluate_result import evaluate_predictions

evaluate_predictions(ground_truths, predictions)

In [ ]:
reasoning_module.entities

In [ ]:
count_path_to_ans(1,  subgraph_data)

In [ ]:
queries[1]